---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: omnifactory-data
  namespace: omnifactory
  labels:
    app: omnifactory
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
