---
apiVersion: v1
kind: Service
metadata:
  name: omnifactory
  namespace: omnifactory
spec:
  ports:
    - name: minecraft
      port: 25565
      targetPort: 25565
      protocol: TCP
    - name: minecraft-rcon
      port: 25575
      targetPort: 25575
      protocol: TCP
  selector:
    app: omnifactory
